一部を除く機密ファイルが混入しないように

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
-echo "Running pre-commit hook"
-
-cd git rev-parse --show-superproject-working-tree --show-toplevel | head -1
+# Check for files with credentials, excluding .env.example
+if git diff --cached --name-only | grep -E 'credentials|\.env' | grep -v '.env.example'; then
+    echo "Error: You have committed a file with credentials."
+    echo "Please remove the file and try again."
+    exit 1
+fi
